language: ruby
cache:    bundler
sudo:     false

script:
  - bundle exec rake

before_install:
  - gem update --system
  - gem install bundler

rvm:
  - 2.3.8
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - ruby-head
  - jruby-9.2.11.1
  - jruby-head

gemfile:
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_60.gemfile
  - gemfiles/rails_edge.gemfile

matrix:
  exclude:
    - rvm: 2.3.8
      gemfile: gemfiles/rails_60.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/rails_60.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.6.6
      gemfile: gemfiles/rails_42.gemfile
    - rvm: 2.7.1
      gemfile: gemfiles/rails_42.gemfile
    - rvm: 2.7.1
      gemfile: gemfiles/rails_50.gemfile
    - rvm: 2.7.1
      gemfile: gemfiles/rails_51.gemfile
    - rvm: 2.7.1
      gemfile: gemfiles/rails_52.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_42.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_50.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_51.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_52.gemfile
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.2.11.1
    - rvm: jruby-head
    - gemfile: gemfiles/rails_edge.gemfile
